name: Build and publish oidc-authservice

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: 
     - master
env:
  DOCKER_USER: amitmukati2604
  IMG: amitmukati2604/oidc-authservice
  ARCH: linux/ppc64le,linux/amd64

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      #if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build multi-arch docker image
      run: |
        make docker-build-multi-arch

    - name: Build and push multi-arch docker image
      #if: github.event_name == 'push'
      run: |
          make docker-build-push-multi-arch